version: '3'
services:
  motus_auth:
    image: yassibra/motus-auth
    ports:
    - "5000:5000"
    restart: always
  motus_score:
    image: yassibra/motus-score
    ports:
    - "9000:9000"
    restart: always
  motus_motus:
    image: yassibra/motus-motus
    ports:
    - "4000:4000"
    restart: always
  motus_front:
    image: yassibra/motus-front
    ports:
    - "3000:3000"
    restart: always
  