version: '3'
services:
  motus_auth:
    image: yassibra/motus-auth
    ports:
    - "5000:5000"
    restart: always
  motus_score:
    image: yassibra/motus-score
    ports:
    - "9000:9000"
    restart: always